modif style form inscription
WildCodeSchool-2023-09/remfr-php-p3-streetarthunter pull request #16
Opened 2024-01-09 21:28 UTC by Stephdu33

ajout style au form inscription

2024-01-09 21:37 UTC, Jeynox commented
Il y a des conflits

2024-01-09 23:22 UTC, Jeynox commented on assets/styles/register.scss
> +    width: 100px;
Ce n'est pas une bonne pratique de mettre en px essaye de le passer en rem s'il te plait

2024-01-09 23:26 UTC, Jeynox requested changes
Tu as fais un travail incroyable bravo, il y a quelques petites modifications a effectuer

2024-01-09 23:26 UTC, Jeynox commented on assets/styles/register.scss
> +    width: 100px;
Ce n'est pas une bonne pratique les px essaye de le passer en rem s'il te plait

2024-01-10 09:00 UTC, vincentr-wcs commented
@Stephdu33 conflits à régler

2024-01-10 14:06 UTC, closed without merging