S4 us ranking page
WildCodeSchool-2023-09/remfr-php-p3-streetarthunter pull request #20
Opened 2024-01-10 23:43 UTC by Dev-Djam

Ajout de la ranking page + fix bug( amélioration des effets de couleur)

2024-01-11 07:16 UTC, Jeynox requested changes

2024-01-11 07:16 UTC, Jeynox commented on templates/ranking/index.html.twig
> +    - Street art hunter
Le {{ parent() }} c'est déjà Street Art Hunter tu devrais mettre "{{ parent() }} - Classement" a la place"

2024-01-11 07:18 UTC, Jeynox commented
il y a une erreur qui bloque sur le fichier 'RanckingController.php' ça ne pourra pas passer pour la PR

2024-01-12 17:08 UTC, Stephdu33 approved these changes

2024-01-14 11:29 UTC, merged