création bdd et entités
WildCodeSchool-2023-09/remfr-php-p3-streetarthunter pull request #3
Opened 2023-12-20 22:53 UTC by Stephdu33

2023-12-20 23:09 UTC, Jeynox requested changes
Il manque certaines notions de inversedBy sur deux tables User et Artist

2023-12-21 09:50 UTC, Jeynox approved these changes
C'est super

2023-12-21 10:13 UTC, Dev-Djam approved these changes
Good

2023-12-21 10:13 UTC, Maximecb83 approved these changes

2023-12-21 10:19 UTC, yavuzkutuk commented
@Stephdu33 conflict

2023-12-21 10:22 UTC, yavuzkutuk approved these changes

2023-12-21 10:22 UTC, merged